version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_bi
    environment:
      POSTGRES_USER: bi_user
      POSTGRES_PASSWORD: bi_password
      POSTGRES_DB: bi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase:v0.45.2
    container_name: metabase_bi
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase_data:/metabase-data

 
  nifi:
    image: apache/nifi:latest
    container_name: nifi_bi
    ports:
      - "8080:8080"
    environment:
      NIFI_WEB_HTTP_PORT: 8080
    volumes:
      - nifi_data:/opt/nifi/nifi-current

  airflow:
    image: apache/airflow:latest
    container_name: airflow_bi
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: 'postgresql+psycopg2://bi_user:bi_password@postgres_bi:5432/bi_db'
      AIRFLOW__CORE__EXECUTOR: 'SequentialExecutor'
    volumes:
      - airflow_home:/opt/airflow
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    entrypoint: /bin/bash -c
    command: >
      "
      airflow db init &&
      airflow users create --username admin --firstname Airflow --lastname Admin --role Admin --email admin@example.com --password admin &&
      airflow webserver
      "

volumes:
  postgres_data:
  metabase_data:
  superset_home:
  nifi_data:
  airflow_home:
